import type { Metadata } from "next";
import "./globals.scss";
import PageSidebar from "@/Components/PageSidebar/PageSidebar";
import PageTransition from "./PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full bg-gray-10 h-full flex gap-2 p-2">
        <PageSidebar></PageSidebar>
        <main
          id="content"
          className="w-full h-full bg-white rounded-xl shadow-md p-4"
        >
          <PageTransition>{children}</PageTransition>
        </main>
      </body>
    </html>
  );
}
